name: Build PETSc Docker images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Run once a week
    - cron: "0 13 * * 1"

jobs:
#######################################################
############## Basic gcc CPU ##########################
#######################################################
  deploy-cpu-bases:
    name: "cpu-base"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"

    steps:
      - name: Checkout devito
        uses: actions/checkout@v4

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: cleanup
        run: docker system prune -a -f

      - name: GCC image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: './docker/Dockerfile.cpu'
          push: true
          target: 'gcc'
          build-args: 'arch=gcc'
          tags: 'zoeleibowitz/bases:cpu-gcc'
