name: CI-petsc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-petsc:
    name: pytest-petsc
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout devito
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install mpich libopenblas-serial-dev -y

    - name: Download and install PETSc
      run: |
        mkdir -p $HOME/petsc
        cd $HOME/petsc
        git clone -b release https://gitlab.com/petsc/petsc.git petsc
        cd petsc
        git pull
        ./configure --with-fortran-bindings=0 --with-blaslapack-dir=/usr/lib/x86_64-linux-gnu PETSC_ARCH=arch-linux-c
        make all
        grep BLASLAPACK_LIB $HOME/petsc/petsc/arch-linux-c/lib/petsc/conf/petscvariables


    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: pytest-petsc